language: node_js

node_js:
- "node"

cache:
  directories:
  - node_modules

env:
  global:
  - GEMFURY_USER=base63

install:
- npm install --registry=https://npm-proxy.fury.io/${GEMFURY_API_KEY}/${GEMFURY_USER}/ --progress=false

script:
- true

deploy:
- provider: script
  skip_cleanup: true
  script: ./src/togemfury.sh --user ${GEMFURY_USER} --api_key ${GEMFURY_API_KEY}
